# Generated by Django 4.2.3 on 2023-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('call_date', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('add_to_chat', models.IntegerField(blank=True)),
                ('call_id', models.CharField(max_length=255)),
                ('record_url', models.FileField(upload_to='rings/')),
            ],
        ),
    ]
