# Generated by Django 4.2.3 on 2023-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0002_alter_callinfo_duration_alter_callinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='add_to_chat',
            field=models.IntegerField(blank=True, choices=[(0, 'Не уведомлять'), (1, 'Уведомлять')]),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
