# Generated by Django 4.2.3 on 2023-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0005_alter_callinfo_add_to_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='call_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
