# Generated by Django 4.2.3 on 2023-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0006_alter_callinfo_call_id_alter_callinfo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
