# Generated by Django 4.2.3 on 2023-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0007_alter_callinfo_call_id_alter_callinfo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='add_to_chat',
            field=models.IntegerField(blank=True, choices=[(0, 'Не уведомлять'), (1, 'Уведомлять')], null=True),
        ),
    ]
