# Generated by Django 4.2.3 on 2023-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0009_alter_callinfo_record_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='record_url',
            field=models.FileField(upload_to='rings/'),
        ),
    ]
