# Generated by Django 4.2.3 on 2023-07-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmp3', '0010_alter_callinfo_record_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='record_url',
            field=models.FileField(blank=True, null=True, upload_to='rings/'),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
    ]
