# Generated by Django 2.2.13 on 2020-11-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=127, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExampleChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('telegram_type', models.CharField(blank=True, choices=[('private', 'private'), ('group', 'group'), ('supergroup', 'supergroup')], default='', max_length=25, null=True)),
                ('secret', models.CharField(blank=True, default='', max_length=50)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example_bot.ExampleBot')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'abstract': False,
            },
        ),
    ]
