# Generated by Django 2.2.13 on 2020-11-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example_bot', '0002_examplechat_exampleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleChatParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='example_bot.ExampleChat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_chats', to='example_bot.ExampleUser')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
                'abstract': False,
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
