# Generated by Django 3.0.7 on 2021-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='workday_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
