# Generated by Django 3.0.7 on 2021-03-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0002_hruser_workday_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr_bot.HrUser')),
            ],
        ),
    ]
