# Generated by Django 4.2.3 on 2023-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bot', '0005_hruser_workday_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmessage',
            name='caption',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='hrmessage',
            name='effective_attachment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrchatparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrcheckpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
